#cloud-config
packages:
  - nfs-kernel-server

runcmd:
  # NFS data
  - admin_home=${base_homedir:-/home}/${admin_user}
  - [[ ${admin_user} == "root" ]] && admin_home=/root
  - mkdir -p /DATA
  - echo "192.168.73.25:/DATA      /DATA      nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - mount -a
  # NFS
  - echo "/shared `hostname -I | awk '{print $1}' | grep -Po '(\d+\.){3}'`0/24(rw,sync,no_root_squash,no_all_squash)" > /etc/exports
  - mkdir -p /shared
  - chown ${admin_user} /shared
  - systemctl enable nfs-kernel-server
  - systemctl restart nfs-kernel-server
  # Kubeadm  
  - echo "SUDO_UID=${admin_user} sudo -E /tmp/kubeadm-bootstrap/init-master.bash" >> /tmp/install.sh
  - su ${admin_user} -c "/tmp/install.sh"
  - kubeadm token create --print-join-command > /shared/kubeadm-join.bash
  - kubectl label nodes `hostname` type=production  
  # k8s commands
  - cat /tmp/kubeadm-bootstrap/.bashrc >> /home/${admin_user}/.bashrc
  # ssh config for nodes
  # make sure that k8s node is ready, and enable easy ssh
  - su ${admin_user} -c "touch ${admin_home}/.ssh/config"
  - mv /tmp/kubeadm-bootstrap/add_nodes.bash ${admin_home}/
  - chmod u+x ${admin_home}/add_nodes.bash
  - su ${admin_user} -c "${admin_home}/add_nodes.bash ${nb_nodes}"
  # Configure docker registry
  - echo "" >> ${admin_home}/.ssh/config;
  - echo "Host registry" >> ${admin_home}/.ssh/config;
  - echo "        HostName "${docker_registry} >> ${admin_home}/.ssh/config;
  - echo "        User "${admin_user} >> ${admin_home}/.ssh/config; 
  - su ${admin_user} -c "sudo docker login ${docker_registry} --username ${docker_id} --password ${docker_password}"
  - while [ ! -d /var/lib/kubelet/ ]; do sleep 1; done; 
  - cp ${admin_home}/.docker/config.json /var/lib/kubelet/
  # creating flag to say that master configuration finished
  - touch /shared/k8s-initialized
